#!/bin/bash
echo "ETAPA3";
echo "00"; cat tests/syntax/input/etapa3/i00.iks | ./main
echo "01"; cat tests/syntax/input/etapa3/i01.iks | ./main
echo "02"; cat tests/syntax/input/etapa3/i02.iks | ./main
echo "03"; cat tests/syntax/input/etapa3/i03.iks | ./main
echo "04"; cat tests/syntax/input/etapa3/i04.iks | ./main
echo "05"; cat tests/syntax/input/etapa3/i05.iks | ./main
echo "06"; cat tests/syntax/input/etapa3/i06.iks | ./main
echo "07"; cat tests/syntax/input/etapa3/i07.iks | ./main
echo "08"; cat tests/syntax/input/etapa3/i08.iks | ./main
echo "09"; cat tests/syntax/input/etapa3/i09.iks | ./main
echo "10"; cat tests/syntax/input/etapa3/i10.iks | ./main
echo "11"; cat tests/syntax/input/etapa3/i11.iks | ./main
echo "12"; cat tests/syntax/input/etapa3/i12.iks | ./main
echo "13"; cat tests/syntax/input/etapa3/i13.iks | ./main
echo "14"; cat tests/syntax/input/etapa3/i14.iks | ./main
echo "15"; cat tests/syntax/input/etapa3/i15.iks | ./main
echo "16"; cat tests/syntax/input/etapa3/i16.iks | ./main
echo "17"; cat tests/syntax/input/etapa3/i17.iks | ./main
echo "18"; cat tests/syntax/input/etapa3/i18.iks | ./main
echo "19"; cat tests/syntax/input/etapa3/i19.iks | ./main
echo "20"; cat tests/syntax/input/etapa3/i20.iks | ./main
echo "21"; cat tests/syntax/input/etapa3/i21.iks | ./main
echo "22"; cat tests/syntax/input/etapa3/i22.iks | ./main
echo "23"; cat tests/syntax/input/etapa3/i23.iks | ./main
echo "24"; cat tests/syntax/input/etapa3/i24.iks | ./main
echo "25"; cat tests/syntax/input/etapa3/i25.iks | ./main
echo "26"; cat tests/syntax/input/etapa3/i26.iks | ./main
echo "27"; cat tests/syntax/input/etapa3/i27.iks | ./main
echo "28"; cat tests/syntax/input/etapa3/i28.iks | ./main
echo "29"; cat tests/syntax/input/etapa3/i29.iks | ./main
echo "30"; cat tests/syntax/input/etapa3/i30.iks | ./main
echo "31"; cat tests/syntax/input/etapa3/i31.iks | ./main
echo "32"; cat tests/syntax/input/etapa3/i32.iks | ./main
echo "33"; cat tests/syntax/input/etapa3/i33.iks | ./main
echo "34"; cat tests/syntax/input/etapa3/i34.iks | ./main
echo "35"; cat tests/syntax/input/etapa3/i35.iks | ./main
echo "36"; cat tests/syntax/input/etapa3/i36.iks | ./main
echo "37"; cat tests/syntax/input/etapa3/i37.iks | ./main
echo "38"; cat tests/syntax/input/etapa3/i38.iks | ./main
echo "39"; cat tests/syntax/input/etapa3/i39.iks | ./main
echo "40"; cat tests/syntax/input/etapa3/i40.iks | ./main
echo "41"; cat tests/syntax/input/etapa3/i41.iks | ./main
echo "42"; cat tests/syntax/input/etapa3/i42.iks | ./main
echo "43"; cat tests/syntax/input/etapa3/i43.iks | ./main
echo "44"; cat tests/syntax/input/etapa3/i44.iks | ./main
echo "45"; cat tests/syntax/input/etapa3/i45.iks | ./main
echo "46"; cat tests/syntax/input/etapa3/i46.iks | ./main
echo "47"; cat tests/syntax/input/etapa3/i47.iks | ./main
echo "48"; cat tests/syntax/input/etapa3/i48.iks | ./main
echo "49"; cat tests/syntax/input/etapa3/i49.iks | ./main
echo "50"; cat tests/syntax/input/etapa3/i50.iks | ./main
